import './globals.css'
import type {Metadata} from 'next'
import {Noto_Sans} from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import React from "react";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {cn} from "@/lib/utils";
import ModalProvider from "@/components/providers/modalProvider";
import {SocketProvider} from "@/components/providers/socketProvider";
import {QueryProvider} from "@/components/providers/queryProvider";


const font = Noto_Sans({subsets: ['latin'], weight: '800',})

export const metadata: Metadata = {
    title: 'Test discord', description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <ClerkProvider>
            <body className={cn(font.className,
                "bg-white dark:bg-black"
            )}>
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem={false}
                storageKey="discord-theme">
                <ModalProvider/>
                <SocketProvider>
                    <QueryProvider>
                        {children}
                    </QueryProvider>
                </SocketProvider>
            </ThemeProvider>
            </body>
        </ClerkProvider>
        </html>
    )
}
